FROM poolingpeople/wildfly
ENV neo4j {NEO_INSTANCE}
#ENV pp_app_environment {test (no_backups)|live (backups)}

ADD standalone.conf /opt/jboss/wildfly/bin/
ADD standalone.xml /opt/jboss/wildfly/standalone/configuration/

RUN /opt/jboss/wildfly/bin/add-user.sh ppuser ppuser0000. --silent
ADD {PP_FINAL_NAME} /opt/jboss/wildfly/standalone/deployments/
EXPOSE 3614
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]