FROM poolingpeople/wildfly:8.1-8_45
ENV neo4j {NEO_INSTANCE}
#ENV pp_app_environment {test (no_backups)|live (backups)}
#ENV pp_app_environment live
ENV pp_app_environment {PP_APP_ENVIRONMENT}
ENV EMAIL_PASSWORD {EMAIL_PASSWORD}

ADD standalone.conf /opt/jboss/wildfly/bin/
ADD standalone.xml /opt/jboss/wildfly/standalone/configuration/

RUN /opt/jboss/wildfly/bin/add-user.sh ppuser ppuser0000. --silent
ADD {PP_FINAL_NAME} /opt/jboss/wildfly/standalone/deployments/
EXPOSE 3614
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]