FROM poolingpeople/wildfly

ADD standalone.conf /opt/jboss/wildfly/bin/
ADD standalone.xml /opt/jboss/wildfly/standalone/configuration/

ENV EMAIL_PASSWORD ${DEPLOYER_EMAIL_PASSWORD}

RUN /opt/jboss/wildfly/bin/add-user.sh ppuser ppuser0000. --silent
ADD deployer.war /opt/jboss/wildfly/standalone/deployments/
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]